$originDir = $(Get-Item ".").FullName
$workDir = "$originDir\work"
$mariadbVer = "10.1.25"
$mroongaVer = "7.05"
$useNightly = $null
#$useReleasePackage = $null
$downloadRequestSkip = $null
$mroongaSourceBaseURI = $null
$mroongaSourceNightlyBaseURI = $null
